### ISSUE TITLE
limitedEntry[key].slice is not a function

### ISSUE THREAD

**Issue by heyjaypray** [DomDew/strapi-plugin-fuzzy-search#157]
I just installed this plugin

Strapi Version:  "@strapi/strapi": "4.20.3",
"strapi-plugin-fuzzy-search": "^2.2.0",

plugins.js

```
 "fuzzy-search": {
    enabled: true,
    config: {
      contentTypes: [
        {
          uid: "api::order.order",
          modelName: "orders",
          fuzzysortOptions: {
            characterLimit: 300,
            keys: [
              {
                name: "orderNum",
                weight: 100,
              },
              {
                name: "poNum",
                weight: 100,
              },
            ],
          },
        },
      ],
    },
  }
```
  
  

  [2024-02-29 16:44:10.116] error: limitedEntry[key].slice is not a function
TypeError: limitedEntry[key].slice is not a function
    at C:\Users\hey\coding\sapele_server\node_modules\strapi-plugin-fuzzy-search\dist\server\services\fuzzySearch-service.js:25:33
    at Array.forEach (<anonymous>)
    at C:\Users\hey\coding\sapele_server\node_modules\strapi-plugin-fuzzy-search\dist\server\services\fuzzySearch-service.js:21:15
    at Array.map (<anonymous>)
    at limitCharacters (C:\Users\hey\coding\sapele_server\node_modules\strapi-plugin-fuzzy-search\dist\server\services\fuzzySearch-service.js:18:68)
    at buildResult (C:\Users\hey\coding\sapele_server\node_modules\strapi-plugin-fuzzy-search\dist\server\services\fuzzySearch-service.js:32:11)
    at getResult (C:\Users\hey\coding\sapele_server\node_modules\strapi-plugin-fuzzy-search\dist\server\services\fuzzySearch-service.js:94:42)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)    
    at async C:\Users\hey\coding\sapele_server\node_modules\strapi-plugin-fuzzy-search\dist\server\controllers\search-controller.js:36:20
    at async Promise.all (index 0)
    
    
    

    I think it has to do with this function

```javascript
const limitCharacters = (entries, characterLimit, keys) => entries.map((entry) => {
    const limitedEntry = { ...entry };
    const entryKeys = Object.keys(limitedEntry);
    entryKeys.forEach((key) => {
        if (!keys.includes(key))
            return;
        limitedEntry[key] = limitedEntry[key]
            ? limitedEntry[key].slice(0, characterLimit)
            : limitedEntry[key];
    });
    return limitedEntry;
});
```

**Comment by heyjaypray** [comment]
The errors leaves when i remove characterLimit from the plugins.js

```
fuzzysortOptions: {
    // characterLimit: 300,
    threshold: -100,
    keys: [
      {
        name: "poNum",
        weight: -100,
      },
      {
        name: "orderNum",
        weight: 200,
      },
    ],
  },
```

**Comment by DomDew** [comment]
Hey @heyjaypray ,

I could reproduce your error. It is due to my oversight, as I always assumed that one would search only in strings and not in numbers. I will fix this asap.

Might I ask you what your specific use case is with fuzzy searching numbers though? Just out of curiosity and getting a grasp of more potential use cases...

**Comment by DomDew** [comment]
Hey @heyjaypray rolling out the fix asap, it seems like GitHub actions and Pull Requests seem to have issues at the moment now which means I can't run my release workflow 😅

**Comment by heyjaypray** [comment]
> Hey @heyjaypray ,
> 
> 
> 
> I could reproduce your error. It is due to my oversight, as I always assumed that one would search only in strings and not in numbers. I will fix this asap.
> 
> 
> 
> Might I ask you what your specific use case is with fuzzy searching numbers though? Just out of curiosity and getting a grasp of more potential use cases...

I'm using numbers to search in my case because I need to look up order numbers

Thanks for the quick update!!
