### ISSUE TITLE
[ERR_INVALID_ARG_TYPE]: The "path" argument must be of type string. Received undefined

### ISSUE THREAD

**Issue by marcelkussin** [DomDew/strapi-plugin-fuzzy-search#49]
I just tried to install your plugin but i can't start it.

strapi 4.5.6

`TypeError [ERR_INVALID_ARG_TYPE]: The "path" argument must be of type string. Received undefined
at new NodeError (node:internal/errors:387:5)
at validateString (node:internal/validators:162:11)
at join (node:path:1172:7)
at Object.loadPlugins (/opt/node_modules/@strapi/strapi/lib/core/loaders/plugins/index.js:88:34)
at async Strapi.loadPlugins (/opt/node_modules/@strapi/strapi/lib/Strapi.js:336:5)
at async Promise.all (index 2)
at async Strapi.register (/opt/node_modules/@strapi/strapi/lib/Strapi.js:372:5)
at async Strapi.load (/opt/node_modules/@strapi/strapi/lib/Strapi.js:477:5)
at async Strapi.start (/opt/node_modules/@strapi/strapi/lib/Strapi.js:212:9)`

i tried to start it with this config:
`"fuzzy-search": {
    enabled: true,
    config: {
      contentTypes: [
        // articles
        {
          uid: "api::feed-item.feed-item",
          modelName: "article",
          transliterate: true,
          queryConstraints: {
            where: {
              $and: [
                {
                  type: 'article',
                },
              ],
            },
          },
          fuzzysortOptions: {
            characterLimit: 100,
            threshold: -600,
            limit: 30,
            keys: [
              {
                name: "name",
                weight: -100,
              },
              {
                name: "shortDescription",
                weight: 200,
              },
              {
                name: "description",
                weight: 100,
              },
            ],
          },
        },
...
`

**Comment by marcelkussin** [comment]
it was my own fault, the plugin wasnt installed in that docker-container i used
