### ISSUE TITLE
Yup dependency issue: ValidationError: contentTypes must be a `array` type, but the final value was: `null`

### ISSUE THREAD

**Issue by ks-devendrak** [DomDew/strapi-plugin-fuzzy-search#92]
I install the plugin with the help of `yarn add strapi-plugin-fuzzy-search` cmd. Then I start the development server and got the below error. 

```bash
$ strapi develop
.../node_modules/yup/lib/util/createValidation.js:54
      const error = new _ValidationError.default(_ValidationError.default.formatError(overrides.message || message, nextParams), value, nextParams.path, overrides.type || name);
                    ^

ValidationError: contentTypes must be a `array` type, but the final value was: `null` (cast from the value `{}`).
 If "null" is intended as an empty value be sure to mark the schema as `.nullable()`
    at Object.createError (.../node_modules/yup/lib/util/createValidation.js:54:21)
    at Object.test (.../node_modules/yup/lib/schema.js:478:76)
    at validate (.../node_modules/yup/lib/util/createValidation.js:71:30)
    at runTests (.../node_modules/yup/lib/util/runTests.js:39:5)
    at ArraySchema._validate (.../node_modules/yup/lib/schema.js:246:27)
    at ArraySchema._validate (.../node_modules/yup/lib/array.js:91:11)
    at ArraySchema.validate (.../node_modules/yup/lib/schema.js:271:51)
    at .../node_modules/yup/lib/object.js:182:17
    at runTests (.../node_modules/yup/lib/util/runTests.js:39:5)
    at .../node_modules/yup/lib/object.js:199:29 {
  value: { contentTypes: null },
  path: 'contentTypes',
  type: 'typeError',
  errors: [
    'contentTypes must be a `array` type, but the final value was: `null` (cast from the value `{}`).\n' +
      ' If "null" is intended as an empty value be sure to mark the schema as `.nullable()`'
  ],
  params: {
    value: null,
    originalValue: {},
    label: undefined,
    path: 'contentTypes',
    type: 'array'
  },
  inner: []
}

Node.js v18.17.1
```

Project dependencies: 
```
"dependencies": {
  "@strapi/plugin-i18n": "4.12.4",
  "@strapi/plugin-users-permissions": "4.12.4",
  "@strapi/strapi": "4.12.4",
  "better-sqlite3": "8.5.0",
  "strapi-plugin-fuzzy-search": "2.0.4"
}
```

Don't know how to fix it.

**Comment by ks-devendrak** [comment]
I resolve the issue by updating the `./config/plugins.js` file.
```
# ./config/plugins.js

module.exports = ({ env }) => ({
  // ...

  "fuzzy-search": {
    enabled: true,
    config: {
      contentTypes: [],
    },
  },

  // ...
});

```
